title = ""
baseURL = "https://djvelimir.github.io/"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Blog"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.ru]
    title = "Блог"
    weight = 2
    contentDir = "content/ru"
  [languages.fi]
    title = "Blogi"
    weight = 3
    contentDir = "content/fi"
  [languages.fr]
    title = "Blogue"
    weight = 4
    contentDir = "content/fr"
  [languages.pt]
    title = "Blog"
    weight = 5
    contentDir = "content/pt"
  [languages.es]
    title = "Blog"
    weight = 6
    contentDir = "content/es"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "favicon.ico"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  
[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/djvelimir"
follow = true
share = true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/djvelimir"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/@road_to_success"

[[params.ananke_socials]]
name = "facebook"
label = "Facebook"
follow = false
share = true

[[params.ananke_socials]]
name = "twitter"
label = "Twitter"
follow = false
share = true
