title = "djvelimir.github.io"
baseURL = "https://djvelimir.github.io/"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true

[taxonomies]
  tag = "tags"
  category = "categories"

[languages]
  [languages.en]
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.ru]
    weight = 2
    contentDir = "content/ru"
  [languages.uk]
    weight = 3
    contentDir = "content/uk"
  [languages.fi]
    weight = 4
    contentDir = "content/fi"
  [languages.fr]
    weight = 5
    contentDir = "content/fr"
  [languages.pt]
    weight = 6
    contentDir = "content/pt"
  [languages.es]
    weight = 7
    contentDir = "content/es"
  [languages.ja]
    weight = 8
    contentDir = "content/ja"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "favicon.ico"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  custom_css = ["custom.css"]

[[params.ananke_socials]]
  name = "twitter"
  label = "Twitter"
  follow = false
  share = true

[[params.ananke_socials]]
  name = "facebook"
  label = "Facebook"
  follow = false
  share = true

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/djvelimir"

[[params.ananke_socials]]
  name = "youtube"
  url = "https://www.youtube.com/@djvelimir"

[[params.ananke_socials]]
  name = "linkedin"
  url = "https://linkedin.com/in/djvelimir"
  follow = true
  share = true
